"""empty message

Revision ID: 88c2daad9909
Revises: 
Create Date: 2020-03-09 18:16:24.006000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88c2daad9909'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RunSuite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=100), nullable=True),
    sa.Column('test_group', sa.String(length=100), nullable=True),
    sa.Column('suiteName', sa.String(length=200), nullable=True),
    sa.Column('suiteDatas', sa.Text(), nullable=True),
    sa.Column('modifyCount', sa.Integer(), nullable=True),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('statu', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('suiteName'),
    sa.UniqueConstraint('test_group'),
    sa.UniqueConstraint('user')
    )
    op.create_table('isMakeUser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_en', sa.String(length=100), nullable=True),
    sa.Column('isMake', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_en')
    )
    op.create_table('key_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_key', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('user_value', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_base_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelName', sa.String(length=100), nullable=True),
    sa.Column('modelLink', sa.String(length=500), nullable=True),
    sa.Column('modelStatus', sa.Boolean(), nullable=True),
    sa.Column('isAdmin', sa.Boolean(), nullable=True),
    sa.Column('levelName', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_api',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project', sa.String(length=100), nullable=True),
    sa.Column('project_en', sa.String(length=100), nullable=True),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('use_status', sa.Integer(), nullable=True),
    sa.Column('test_group', sa.String(length=100), nullable=True),
    sa.Column('startDate', sa.DateTime(), nullable=True),
    sa.Column('endDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project')
    )
    op.create_table('runSuiteProject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project', sa.String(length=100), nullable=True),
    sa.Column('project_en', sa.String(length=100), nullable=True),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('use_status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project'),
    sa.UniqueConstraint('project_en')
    )
    op.create_table('telephone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('env', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_domain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('statu', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('test_env',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('env_flag', sa.String(length=100), nullable=True),
    sa.Column('env_num', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('developer', sa.String(length=100), nullable=True),
    sa.Column('report_url', sa.String(length=100), nullable=True),
    sa.Column('success_count', sa.String(length=100), nullable=True),
    sa.Column('fail_count', sa.String(length=100), nullable=True),
    sa.Column('mistake_count', sa.String(length=100), nullable=True),
    sa.Column('cookies', sa.String(length=100), nullable=True),
    sa.Column('createDate', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_http_api',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project', sa.String(length=100), nullable=True),
    sa.Column('case_api', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('case_host', sa.String(length=500), nullable=True),
    sa.Column('case_url', sa.String(length=500), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('params', sa.Text(), nullable=True),
    sa.Column('headers', sa.Text(), nullable=True),
    sa.Column('cookies', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('isLogin', sa.Boolean(), nullable=True),
    sa.Column('account_project', sa.String(length=100), nullable=True),
    sa.Column('account_username', sa.String(length=100), nullable=True),
    sa.Column('account_passwd', sa.String(length=100), nullable=True),
    sa.Column('isSchedule', sa.Boolean(), nullable=True),
    sa.Column('checkAssert', sa.String(length=100), nullable=True),
    sa.Column('test_env', sa.String(length=100), nullable=True),
    sa.Column('test_group', sa.String(length=100), nullable=True),
    sa.Column('tester', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['project'], ['project_api.project'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suiteDatas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.Column('suiteData', sa.Text(), nullable=True),
    sa.Column('suiteName', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['api_id'], ['case_http_api.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suiteDatas')
    op.drop_table('case_http_api')
    op.drop_table('test_report')
    op.drop_table('test_env')
    op.drop_table('test_domain')
    op.drop_table('telephone')
    op.drop_table('runSuiteProject')
    op.drop_table('project_api')
    op.drop_table('model_set')
    op.drop_table('login_base_project')
    op.drop_table('key_value')
    op.drop_table('isMakeUser')
    op.drop_table('RunSuite')
    # ### end Alembic commands ###


def upgrade_qa_user():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Dept',
    sa.Column('deptId', sa.Integer(), nullable=False),
    sa.Column('deptName', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('deptId')
    )
    op.create_table('SystemMessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fromUser', sa.String(length=100), nullable=True),
    sa.Column('toUser', sa.String(length=100), nullable=True),
    sa.Column('msg', sa.Text(), nullable=True),
    sa.Column('params', sa.String(length=200), nullable=True),
    sa.Column('func', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('createDate', sa.DateTime(), nullable=False),
    sa.Column('userId', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Manager',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('userName', sa.String(length=100), nullable=True),
    sa.Column('deptId', sa.Integer(), nullable=True),
    sa.Column('passwd', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['deptId'], ['Dept.deptId'], ),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_table('User',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('userName', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('deptId', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('mail', sa.String(length=100), nullable=True),
    sa.Column('imgUrl', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['deptId'], ['Dept.deptId'], ),
    sa.PrimaryKeyConstraint('userId')
    )
    # ### end Alembic commands ###


def downgrade_qa_user():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    op.drop_table('Manager')
    op.drop_table('SystemMessage')
    op.drop_table('Dept')
    # ### end Alembic commands ###

