"""empty message

Revision ID: c437b1d61a67
Revises: 
Create Date: 2020-04-30 17:48:04.144000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c437b1d61a67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('case_http_api', 'test_env',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('case_http_api', 'test_group',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_table_comment(
        'case_http_api',
        existing_comment=u'\u63a5\u53e3\u7528\u4f8b\u8868',
        schema=None
    )
    op.drop_table_comment(
        'case_http_file',
        existing_comment=u'\u63a5\u53e3\u4e0a\u4f20\u7528\u4f8b\u8868',
        schema=None
    )
    op.create_unique_constraint(None, 'isMakeUser', ['project_en'])
    op.drop_table_comment(
        'isMakeUser',
        existing_comment=u'\u9879\u76ee\u521b\u5efa\u7528\u6237\u914d\u7f6e\u8868',
        schema=None
    )
    op.drop_table_comment(
        'login_base_project',
        existing_comment=u'\u767b\u5f55\u7cfb\u7edf\u914d\u7f6e\u8868',
        schema=None
    )
    op.drop_table_comment(
        'model_set',
        existing_comment=u'\u7cfb\u7edf\u83dc\u5355\u914d\u7f6e\u8868',
        schema=None
    )
    op.alter_column('project_api', 'endDate',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text(u'CURRENT_TIMESTAMP'))
    op.alter_column('project_api', 'startDate',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text(u'CURRENT_TIMESTAMP'))
    op.alter_column('project_api', 'test_group',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('project_api', 'use_status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_table_comment(
        'project_api',
        existing_comment=u'\u4e1a\u52a1\u9879\u76ee\u914d\u7f6e\u8868',
        schema=None
    )
    op.drop_table_comment(
        'runSuiteProject',
        existing_comment=u'\u6301\u7eed\u8c03\u5ea6\u4e1a\u52a1\u6d41\u7a0b\u9879\u76ee\u914d\u7f6e\u8868',
        schema=None
    )
    op.drop_index('case_http_api', table_name='suiteDatas')
    op.drop_table_comment(
        'suiteDatas',
        existing_comment=u'\u4f20\u9012\u63a5\u53e3\u53c2\u6570\u8868',
        schema=None
    )
    op.drop_table_comment(
        'telephone',
        existing_comment=u'\u6d4b\u8bd5\u53f7\u7801\u7ba1\u7406\u8868',
        schema=None
    )
    op.create_unique_constraint(None, 'test_domain', ['domain'])
    op.drop_table_comment(
        'test_domain',
        existing_comment=u'\u529f\u80fd\u57df\u914d\u7f6e\u8868',
        schema=None
    )
    op.drop_table_comment(
        'test_env',
        existing_comment=u'\u6d4b\u8bd5\u73af\u5883\u914d\u7f6e\u8868',
        schema=None
    )
    op.alter_column('test_report', 'cookies',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('test_report', 'createDate',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text(u'CURRENT_TIMESTAMP'))
    op.alter_column('test_report', 'type',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_table_comment(
        'test_report',
        existing_comment=u'\u6d4b\u8bd5\u62a5\u544a\u6570\u636e\u8868',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'test_report',
        u'\u6d4b\u8bd5\u62a5\u544a\u6570\u636e\u8868',
        existing_comment=None,
        schema=None
    )
    op.alter_column('test_report', 'type',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('test_report', 'createDate',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text(u'CURRENT_TIMESTAMP'))
    op.alter_column('test_report', 'cookies',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.create_table_comment(
        'test_env',
        u'\u6d4b\u8bd5\u73af\u5883\u914d\u7f6e\u8868',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'test_domain',
        u'\u529f\u80fd\u57df\u914d\u7f6e\u8868',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'test_domain', type_='unique')
    op.create_table_comment(
        'telephone',
        u'\u6d4b\u8bd5\u53f7\u7801\u7ba1\u7406\u8868',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'suiteDatas',
        u'\u4f20\u9012\u63a5\u53e3\u53c2\u6570\u8868',
        existing_comment=None,
        schema=None
    )
    op.create_index('case_http_api', 'suiteDatas', ['id'], unique=False)
    op.create_table_comment(
        'runSuiteProject',
        u'\u6301\u7eed\u8c03\u5ea6\u4e1a\u52a1\u6d41\u7a0b\u9879\u76ee\u914d\u7f6e\u8868',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'project_api',
        u'\u4e1a\u52a1\u9879\u76ee\u914d\u7f6e\u8868',
        existing_comment=None,
        schema=None
    )
    op.alter_column('project_api', 'use_status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('project_api', 'test_group',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('project_api', 'startDate',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text(u'CURRENT_TIMESTAMP'))
    op.alter_column('project_api', 'endDate',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text(u'CURRENT_TIMESTAMP'))
    op.create_table_comment(
        'model_set',
        u'\u7cfb\u7edf\u83dc\u5355\u914d\u7f6e\u8868',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'login_base_project',
        u'\u767b\u5f55\u7cfb\u7edf\u914d\u7f6e\u8868',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'isMakeUser',
        u'\u9879\u76ee\u521b\u5efa\u7528\u6237\u914d\u7f6e\u8868',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'isMakeUser', type_='unique')
    op.create_table_comment(
        'case_http_file',
        u'\u63a5\u53e3\u4e0a\u4f20\u7528\u4f8b\u8868',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'case_http_api',
        u'\u63a5\u53e3\u7528\u4f8b\u8868',
        existing_comment=None,
        schema=None
    )
    op.alter_column('case_http_api', 'test_group',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('case_http_api', 'test_env',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
